#!/usr/bin/python 
import os, string, sys
# base = input
def toDecimal(input, base = 2): return sum([(base ** pos) * string.atoi(i) for pos, i in enumerate(input[::-1])])
print toDecimal(sys.argv[1])
