#!/usr/bin/php
<?php
	function ipcount($version, $size) { 
		switch ($version) { 
			case "4":
				$power = 32 - $size;  
				$cmd   = sprintf("echo 2^%s | bc", $power); 
				$total = `$cmd`; 
				break; 
			case "6": 
				$power = 128 - $size; 
				$cmd   = sprintf("echo 2^%s | bc", $power); 
				$total = `$cmd`; 
				break; 
		}
	
		return str_replace("\n", "", $total); 
	}

        function csplice($number) {
		$number = str_replace("\n", "", $number); 
                $na = str_split($number, 1);
                for ($i = strlen($number) - 3; $i > 0; $i-=3) {
                        array_splice($na, $i, 0, ",");
                }

                $ret = implode("", $na);
                return $ret;
        }

	
	array_shift($argv); 
	echo sprintf("IPv%s /%s: %s\n", $argv[0], $argv[1], csplice(ipcount($argv[0], $argv[1])));  
?>
