#!/usr/bin/php
<?php
	function ipcount($version, $size) { 
		switch ($version) { 
			case "4":
				$power = 32 - $size;  
				$cmd   = sprintf("echo 2^%s | bc", $power); 
				$total = `$cmd`; 
				break; 
			case "6": 
				$power = 128 - $size; 
				$cmd   = sprintf("echo 2^%s | bc", $power); 
				$total = `$cmd`; 
				break; 
		}
	
		return str_replace("\n", "", $total); 
	}

        function csplice($number) {
		$number = str_replace("\n", "", $number); 
                $na = str_split($number, 1);
                for ($i = strlen($number) - 3; $i > 0; $i-=3) {
                        array_splice($na, $i, 0, ",");
                }

                $ret = implode("", $na);
                return $ret;
        }
	
	function subnetCount($version, $first, $second) { 
		return csplice(ipcount($version, $second) / ipcount($version, $first)); 
	}

	$file = $argv[0]; 
	array_shift($argv); 
	if ($argc == 3) {
		echo sprintf("IPv%s /%s: %s\n", $argv[0], $argv[1], csplice(ipcount($argv[0], $argv[1])));  
	} else if ($argc == 4) {
		if ($argv[1] < $argv[2]) { 
			die(sprintf("Syntax error: %s <version> <larger subnet> <smaller subnet>\n", $file)); 
		}
		echo sprintf("IPv%s: %s /%s's in a /%s\n", $argv[0], subnetCount($argv[0], $argv[1], $argv[2]), $argv[1], $argv[2]);
	}
?>
