#!/usr/bin/php
<?php
	function ipcount($version, $size) { 
		switch ($version) { 
			case "4":
				$power = 32 - $size;  
				$cmd   = sprintf("echo 2^%s | bc", $power); 
				$total = `$cmd`; 
				break; 
			case "6": 
				$power = 128 - $size; 
				$cmd   = sprintf("echo 2^%s | bc", $power); 
				$total = `$cmd`; 
				break; 
		}
	
		return str_replace("\n", "", $total); 
	}

        function csplice($number) {
		$number = str_replace("\n", "", $number); 
                $na = str_split($number, 1);
                for ($i = strlen($number) - 3; $i > 0; $i-=3) {
                        array_splice($na, $i, 0, ",");
                }

                $ret = implode("", $na);
                return $ret;
        }
	
	function subnetCount($version, $first, $second) { 
		return csplice(ipcount($version, $second) / ipcount($version, $first)); 
	}

	$file = $argv[0]; 
	array_shift($argv); 
	if ($argc == 2) {
		echo sprintf("IPv6 /%s: %s\n", $argv[0], csplice(ipcount(6, $argv[0])));  
	} else if ($argc == 3) { 
                if ($argv[0] < $argv[1]) { 
                        die(sprintf("Syntax error: %s <version> <larger subnet> <smaller subnet>\n", $file)); 
                }   
		echo sprintf("IPv6: %s /%s's in a /%s\n", subnetCount(6, $argv[0], $argv[1]), $argv[0], $argv[1]);
	}
?>
