#!/usr/bin/php
<?php
	/* @author JasonKurtz 
	 * @description A simple PHP script to generate a string of random characters of a specified length. 
	 * @version 0.1
	 * @syntax ./randpw [length]
	 * @example ./randpw 10 (Generate a random string of 10 characters)
	 */ 

        function GenRand($len = 10) {
                if (@is_readable('/dev/urandom')) {
                        $f=fopen('/dev/urandom', 'r');
                        $urandom=fread($f, $len);
                        fclose($f);
                }

                $value='';

                for ($i=0;$i<$len;++$i) {

                        if (!isset($urandom)) {
                                if ($i%2==0) {
                                        mt_srand(time()%2147 * 1000000 + (double)microtime() * 1000000);
                                }

                                $rand=48+mt_rand()%64;
                        } else {
                                $rand=48+ord($urandom[$i])%64;
                        }

                        if ($rand>57)
                                $rand+=7;
                        if ($rand>90)
                                $rand+=6;

                        if ($rand==123)
                                $rand=45;
                        if ($rand==124)
                                $rand=46;

                        $value.=chr($rand);
                }

                return $value;
        }
	if (!isset($argv[1]) || !is_numeric($argv[1]))
		$len = 10; 
	else
		$len = $argv[1]; 
	printf("Random string(%d): %s\n", $len, GenRand($len)); 
?>
